### ISSUE TITLE
下载项目后在idea运行，运行结果的页面只有静态网页，没有渲染的动态效果。请问如何正确运行该项目？

### ISSUE THREAD

**Issue by FunnyExplorer** [wsk1103/Used-Trading-Platform#19]

**Comment by haihai33** [comment]
怎么在idea上运行的？我是idea新手，求教

**Comment by ticks8** [comment]
貌似在tomcat里把css，js的包导进去就好了，具体做法和作者sql文件夹里那个教你把image导进来一样

**Comment by Blizzard-M** [comment]
> 假装在tomcat里css，js的包导进去把似的，具体的角色和作者sql里的那个人教你把形象导入一样

老哥可以教一下吗 新手  我怎么都跑不起来  可否留个联系方式  ，或者你加我QQ842266438 可以吗  谢谢了

**Comment by ticks8** [comment]
我当初也遇到过这个问题，我是在这个界面点击+号把css和js文件引进来解决的，希望对你有帮助



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Blizzard-M ***@***.***&gt;
发送时间: 2021年6月18日 01:14
收件人: wsk1103/Used-Trading-Platform ***@***.***&gt;
抄送: ticks8 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[wsk1103/Used-Trading-Platform] 下载项目后在idea运行，运行结果的页面只有静态网页，没有渲染的动态效果。请问如何正确运行该项目？ (#19)





  
假装在tomcat里css，js的包导进去把似的，具体的角色和作者sql里的那个人教你把形象导入一样
  
老哥可以教一下吗 新手  我怎么都跑不起来  可否留个联系方式  ，或者你加我QQ842266438 可以吗  谢谢了

**Comment by Blizzard-M** [comment]
不行啊 老哥    可以给个联系方式指导一下吗










在 2021-06-18 01:36:05，"ticks8" ***@***.***> 写道：

我当初也遇到过这个问题，我是在这个界面点击+号把css和js文件引进来解决的，希望对你有帮助



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Blizzard-M ***@***.***&gt;
发送时间: 2021年6月18日 01:14
收件人: wsk1103/Used-Trading-Platform ***@***.***&gt;
抄送: ticks8 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[wsk1103/Used-Trading-Platform] 下载项目后在idea运行，运行结果的页面只有静态网页，没有渲染的动态效果。请问如何正确运行该项目？ (#19)






假装在tomcat里css，js的包导进去把似的，具体的角色和作者sql里的那个人教你把形象导入一样

老哥可以教一下吗 新手 我怎么都跑不起来 可否留个联系方式 ，或者你加我QQ842266438 可以吗 谢谢了
