### ISSUE TITLE
说说自己在部署上面遇到的问题

### ISSUE THREAD

**Issue by ticks8** [wsk1103/Used-Trading-Platform#36]
1.css，image等不加载，解决办法：
打开tomcat配置，在Deployment中导入css，js文件即可

2.初始界面能打开，但是点击其他页面返回404：
这个只要把application context设置成/
（这应该是很简单大部分人都不会犯的简单错误吧，只是希望能帮到和我一样的小白）

**Comment by NeglectOverlook** [comment]
> 1.css，image等不加载，解决办法： 打开tomcat配置，在Deployment中导入css，js文件即可
> 
> 2.初始界面能打开，但是点击其他页面返回404： 这个只要把application context设置成/ （这应该是很简单大部分人都不会犯的简单错误吧，只是希望能帮到和我一样的小白）

兄弟能把你运行起来的工程打包发一下吗，我整了2天没运行起来。邮箱2861617114@qq.com，感谢了兄弟

**Comment by zhangzhijie1** [comment]
> 

老兄你问题解决了？可以发我一份？

**Comment by kikia7** [comment]
在tomcat导入了css，js文件，运行出来还是不加载呜呜呜

**Comment by JJboom123** [comment]
> 1.css，image等不加载，解决办法： 打开tomcat配置，在Deployment中导入css，js文件即可
> 
> 2.初始界面能打开，但是点击其他页面返回404： 这个只要把application context设置成/ （这应该是很简单大部分人都不会犯的简单错误吧，只是希望能帮到和我一样的小白）

拜托大佬 能发一份你运行起来的项目嘛  谢谢 1045803424@qq.com
