### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by 2212130980** [wsk1103/Used-Trading-Platform#7]
不说成功也不说失败

**Comment by wsk1103** [comment]
我都是可以登录的，运行的时候，你打断点就知道原因了

**Comment by 2212130980** [comment]
是不是不能注册，手机在获取验证码的时候一直说该手机码号被注册，看了代码发现很多代码被注释了。




------------------ 原始邮件 ------------------
发件人: "wsk1103"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 晚上9:05
收件人: "wsk1103/mySSM"<mySSM@noreply.github.com>;
抄送: "Leslie"<2212130980@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wsk1103/mySSM] 无法登陆 (#7)




我都是可以登录的，运行的时候，你打断点就知道原因了

**Comment by userPuti** [comment]
会话刷新自动消失

**Comment by selloum** [comment]
无法登陆+1，跳转白页
