### ISSUE TITLE
是不是没有实现结算功能

### ISSUE THREAD

**Issue by 2212130980** [wsk1103/Used-Trading-Platform#8]
博主

**Comment by selloum** [comment]
你成功登陆了吗

**Comment by 2212130980** [comment]
我成功登录了，但是点击结算没有用




------------------ 原始邮件 ------------------
发件人: "Mana"<notifications@github.com>; 
发送时间: 2019年5月23日(星期四) 晚上8:44
收件人: "wsk1103/mySSM"<mySSM@noreply.github.com>; 
抄送: "Leslie"<2212130980@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wsk1103/mySSM] 是不是没有实现结算功能 (#8)




你成功登陆了吗

**Comment by selloum** [comment]
他的这个是不能结算的，你是怎么登陆的？我输入他的用户名和密码无法登陆，
用户名：123 密码：qq12345 无法跳转，可以告诉我你是怎么登录成功的吗？


------------------ 原始邮件 ------------------
发件人: 2212130980 <notifications@github.com>
发送时间: 2019年5月23日 21:10
收件人: wsk1103/mySSM <mySSM@noreply.github.com>
抄送: Mana <976791255@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[wsk1103/mySSM] 是不是没有实现结算功能 (#8)



我成功登录了，但是点击结算没有用 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "Mana"<notifications@github.com>;  
 发送时间: 2019年5月23日(星期四) 晚上8:44 
 收件人: "wsk1103/mySSM"<mySSM@noreply.github.com>;  
 抄送: "Leslie"<2212130980@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [wsk1103/mySSM] 是不是没有实现结算功能 (#8) 
 
 
 
 
 你成功登陆了吗

**Comment by 2212130980** [comment]
他是根据数据库的手机号来登录的，密码是md5加密的
------------------ 原始邮件 ------------------
发件人: "Mana"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 晚上9:13
收件人: "wsk1103/mySSM"<mySSM@noreply.github.com>;
抄送: "Leslie"<2212130980@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wsk1103/mySSM] 是不是没有实现结算功能 (#8)



他的这个是不能结算的，你是怎么登陆的？我输入他的用户名和密码无法登陆， 
 用户名：123 密码：qq12345 无法跳转，可以告诉我你是怎么登录成功的吗？ 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 2212130980 <notifications@github.com> 
 发送时间: 2019年5月23日 21:10 
 收件人: wsk1103/mySSM <mySSM@noreply.github.com> 
 抄送: Mana <976791255@qq.com>, Comment <comment@noreply.github.com> 
 主题: 回复：[wsk1103/mySSM] 是不是没有实现结算功能 (#8) 
 
 
 
 我成功登录了，但是点击结算没有用  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "Mana"<notifications@github.com>;   
  发送时间: 2019年5月23日(星期四) 晚上8:44  
  收件人: "wsk1103/mySSM"<mySSM@noreply.github.com>;   
  抄送: "Leslie"<2212130980@qq.com>; "Author"<author@noreply.github.com>;   
  主题: Re: [wsk1103/mySSM] 是不是没有实现结算功能 (#8)  
   
   
   
   
  你成功登陆了吗

**Comment by DizzyFrog** [comment]
> 我成功登录了，但是点击结算没有用
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Mana"<notifications@github.com>; 发送时间: 2019年5月23日(星期四) 晚上8:44 收件人: "wsk1103/mySSM"<mySSM@noreply.github.com>; 抄送: "Leslie"<2212130980@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [wsk1103/mySSM] 是不是没有实现结算功能 (#8) 你成功登陆了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

请问下是账号密码是什么?登录远端网页的话
